name: SonarQube Analysis for Frontend

on:
  pull_request:
    paths:
      - "frontend/**"

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (required for the React project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.1"

      # Install dependencies for the frontend
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Build the frontend project
      - name: Build the frontend
        working-directory: frontend
        run: npm run build

        # Install SonarScanner
      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli.zip -d $HOME
          export PATH=$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH

      # Run SonarQube analysis on the frontend folder
      - name: Run SonarQube
        run: |
          sonar-scanner \
            -Dsonar.projectKey=zjefersound_agorium \
            -Dsonar.sources=frontend \
            -Dsonar.language=js \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Optional: Check SonarQube Quality Gate
      - name: Check Quality Gate
        run: |
          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=zjefersound_agorium" | jq -r .projectStatus.status)
          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed with status: $STATUS"
            exit 1
          fi
